# Generated by Django 3.1.2 on 2020-11-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_place_information_end_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='bird_orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(blank=True, default='NULL', max_length=255, unique=True)),
                ('brief_description', models.CharField(blank=True, default='NULL', max_length=255)),
                ('order_image', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.DeleteModel(
            name='place_information',
        ),
    ]
