# Generated by Django 3.1.2 on 2020-11-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20201116_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird_orders',
            name='order_image',
            field=models.ImageField(blank=True, default='NULL', upload_to='photos'),
        ),
    ]
