# Generated by Django 3.1.2 on 2020-11-16 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20201116_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='bird_families',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(blank=True, default='NULL', max_length=255, unique=True)),
                ('brief_description', models.CharField(blank=True, default='NULL', max_length=255)),
                ('bird_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.bird_orders')),
            ],
        ),
    ]
