# Generated by Django 3.1.2 on 2020-11-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_bird_families'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird_families',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bird_orders',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
