# Generated by Django 3.1.2 on 2020-11-16 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20201116_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bird_families',
            old_name='bird_order',
            new_name='bird_orders',
        ),
    ]
