# Generated by Django 3.1.2 on 2020-11-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20201116_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird_families',
            name='brief_description',
            field=models.CharField(blank=True, default='NULL', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bird_orders',
            name='brief_description',
            field=models.CharField(blank=True, default='NULL', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bird_orders',
            name='order_image',
            field=models.ImageField(blank=True, default='NULL', null=True, upload_to='photos'),
        ),
    ]
