# Generated by Django 3.1.2 on 2020-11-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20201116_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='birds_bill_shapes',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('bill_shape', models.CharField(default='NULL', max_length=25, null=True)),
                ('bill_example', models.ImageField(blank=True, null=True, upload_to='photos')),
            ],
        ),
    ]
