# Generated by Django 3.1.2 on 2020-11-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_birds_body_shapes'),
    ]

    operations = [
        migrations.CreateModel(
            name='birds_wing_shapes',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('wing_shape', models.CharField(default='NULL', max_length=25, null=True)),
                ('wing_example', models.ImageField(blank=True, null=True, upload_to='photos')),
            ],
        ),
    ]
