# Generated by Django 3.1.2 on 2020-11-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_birds_wing_shapes'),
    ]

    operations = [
        migrations.CreateModel(
            name='conservation_status',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('conservation_category', models.CharField(default='NULL', max_length=10, null=True)),
                ('conservation_state', models.CharField(default='NULL', max_length=25, null=True)),
            ],
        ),
    ]
