# Generated by Django 3.1.2 on 2020-11-17 20:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0015_birds'),
    ]

    operations = [
        migrations.CreateModel(
            name='sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2020, 11, 17, 12, 2, 38, 303063))),
                ('location', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True, null=True)),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.birds')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
